
version: "3.9"

services:
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacnet

  postgres:
    image: postgres:16-alpine
    container_name: guac_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: supersecret_password
      POSTGRES_DB: guacamole_db
    volumes:
      - guac_db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole:1.5.5
    container_name: guacamole
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd

      # âœ… Use the correct variable names:
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: supersecret_password
    depends_on:
      - guacd
      - postgres
    networks:
      - guacnet
  kali_ssh:
    image: kali-ssh
    container_name: kali_ssh
    restart: unless-stopped
    networks:
      - guacnet

networks:
  guacnet:

volumes:
  guac_db:
